/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designs;

import code.BeanCommGroup;
import code.BeanCommInfo;
import code.BeanCommTrans;
import code.BeanDetails;
import code.CommGroupOperations;
import code.CommGrpMemOperations;
import code.CommInfoOperations;
import code.CommTransactionOperations;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karan
 */
public class Committee_Transactions extends javax.swing.JInternalFrame {

    /**
     * Creates new form Committee_Transactions
     */
          ArrayList<BeanCommGroup> cg;
          ArrayList<BeanCommTrans> list;
          int row;
          String gid,uid,termno;
    public Committee_Transactions() {
        initComponents();
        emptyTable();
        String cgs="Select *,date_format(startdate,'%D of %M, %Y'),date_format(enddate,'%D of %M, %Y'),date_format(collectiondate,'%D of %M, %Y') from committeegroup";
         cg= new CommGroupOperations().retrieveGroup(cgs);
         Update.setEnabled(false);
         if(cg!=null)
         {
        for(BeanCommGroup l:cg)
        {
            cbGId.addItem(""+l.getGrpId());
            
        }
       }
         
    }
       public void emptyTable()
    {
    String[] columnNames = {"Group Id","User Id ", "First Name","Last Name","Term No","Amount","Deposite Date"};

              Object[][] data ;
              data = new Object[0][columnNames.length];
                DefaultTableModel dtm = new DefaultTableModel(data, columnNames)
                {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

             jTable1.setModel(dtm);
    }
     public void display(String str)
    {
         String[] columnNames = {"Group Id","User Id ", "First Name","Last Name","Term No","Amount","Deposite Date"};
        Object[][] data = null;
        list=new CommTransactionOperations().retrieve(str);
        if(list!=null)
        {
                  int i=0;
                  data = new Object[list.size()][columnNames.length];
                  for (BeanCommTrans s : list) 
                  {
                    data[i] = new Object[]{s.getGId(),s.getUId(),s.getFirst(),s.getLast(),s.getTerm(),s.getAmount(),s.getDDate()};
                    i++;
                    
                  }
                  
                  
                DefaultTableModel dtm = new DefaultTableModel(data, columnNames)
                {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

                  jTable1.setModel(dtm);
  
        }
        else
        {
            data = new Object[1][columnNames.length];
            data[0] = new Object[]{"No Record Found","No Record Found","No Record Found","No Record Found","No Record Found","No Record Found"};
                DefaultTableModel dtm = new DefaultTableModel(data, columnNames)
                {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };


             jTable1.setModel(dtm);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel1 = new designs.MyPanel();
        lGrpid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbGId = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbUId = new javax.swing.JComboBox();
        txtAmount = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        txtTermNo = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        lGrpid.setFont(new java.awt.Font("High Tower Text", 1, 36)); // NOI18N
        lGrpid.setText("     Transactions");
        lGrpid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" User Id/Name   :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("   Group ID        :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("  Term No        :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Deposite Date  :   ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("     Amount      :");

        cbGId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        cbGId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGIdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cbUId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        cbUId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUIdActionPerformed(evt);
            }
        });

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        Submit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designs/close.png"))); // NOI18N
        jButton5.setToolTipText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setText("Remove");
        Update.setPreferredSize(new java.awt.Dimension(77, 23));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        txtTermNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTermNoActionPerformed(evt);
            }
        });
        txtTermNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTermNoKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designs/t.PNG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(435, 435, 435))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(256, 256, 256))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txtTermNo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAmount))
                                    .addGap(256, 256, 256))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(435, 435, 435)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(lGrpid, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))))))
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(myPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(myPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lGrpid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)))
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbGId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbUId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTermNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGIdActionPerformed
        // TODO add your handling code here:
        //cbUId.removeAllItems
        int c;
         if(cbGId.getSelectedIndex()>0) 
         {
        cbUId.removeAllItems();
       int id=Integer.parseInt((String) cbGId.getSelectedItem());
            //System.out.println(id);
            String s="select a.User_Id,b.FirstName,b.LastName,b.ContactNo,b.EmailId from groupmember a,logindetails b where a.User_Id=b.User_Id and groupid="+id;
           ArrayList<BeanDetails> l=new CommGrpMemOperations().allMembers(s);
            cbUId.addItem("-Select");
            if(l!=null)
            {
           for(BeanDetails m:l)
           {
             cbUId.addItem(""+m.getUserId()+"-"+m.getFirst()+" "+m.getLast());

           }
            }
           c=Integer.parseInt((String) cbGId.getSelectedItem());
        String st="Select b.groupid,a.termamount  from committeegroup b,committeeinfo a where b.committeeid=a.committeeid and groupid="+c;
        int amount=new CommTransactionOperations().getAmount(st);
        if(amount!=-1)
        {
            txtAmount.setText(""+amount);
            txtAmount.setEnabled(false);
        }
        else    txtAmount.setText("Error");

      
         }
         if(cbGId.getSelectedIndex()>0)
         {
             c=Integer.parseInt((String) cbGId.getSelectedItem());
         String entry="Select a.User_Id,a.FirstName,a.LastName,b.groupid,b.termno,b.amount,date_format(b.depositdate,'%D of %M, %Y')as ddate from logindetails a,transactionentry b where a.User_Id=b.User_Id and groupid="+c+" order by termno";
         display(entry);
         }
    }//GEN-LAST:event_cbGIdActionPerformed

    private void cbUIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUIdActionPerformed
        // TODO add your handling code here:
        
      
         if(cbUId.getSelectedIndex()>0 &&cbGId.getSelectedIndex()>0)
        {
          String []s=((String)cbUId.getSelectedItem()).split("-");
          // System.out.print(s[0]);
          int i=new CommTransactionOperations().getTermNo( Integer.parseInt((String)cbGId.getSelectedItem()),Integer.parseInt(s[0]));
          if(i!=-1)
          {    
              txtTermNo.setText(""+i);
              txtTermNo.setEnabled(false);
          }
          else System.out.println("Error");
          
        }

    }//GEN-LAST:event_cbUIdActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        if(cbGId.getSelectedIndex()>0 && cbUId.getSelectedIndex()>0 && jDateChooser1.getDate()!=null && txtAmount.getText().trim().length()>0)
        {
           int c=Integer.parseInt((String) cbGId.getSelectedItem());

            BeanCommTrans data=new BeanCommTrans();
            String []s=((String)cbUId.getSelectedItem()).split("-");
            int uid=Integer.parseInt(s[0]);
            int term=Integer.parseInt(txtTermNo.getText().trim());
            data.setGId(c);
            String st="Select a.User_Id,a.FirstName,a.LastName,b.groupid,b.termno,b.amount,date_format(b.depositdate,'%D of %M, %Y')as ddate from logindetails a,transactionentry b where a.User_Id=b.User_Id and groupid="+c+" order by termno";
            list=new CommTransactionOperations().retrieve(st);
            String ans="no";
            if(list!=null)
            {   
            for(BeanCommTrans li:list)
            {
                if(uid==li.getUId() && term==li.getTerm())
                {
                    ans="Exist";
                    break;
                }
            }
            }
           if(ans.equals("no"))
           { 
           System.out.print(s[0]);
           data.setUId(uid);
           data.setTerm( term);
           data.setAmount(Integer.parseInt(txtAmount.getText().trim()));
            SimpleDateFormat format=new SimpleDateFormat("yyy/MM/dd");

           data.setDate(format.format(jDateChooser1.getDate()));
           
           if(new CommTransactionOperations().Entry(data))
           {
               JOptionPane.showMessageDialog(null,"Entered Successfully");
                 c=Integer.parseInt((String) cbGId.getSelectedItem());
             String entry="Select a.User_Id,a.FirstName,a.LastName,b.groupid,b.termno,b.amount,date_format(b.depositdate,'%D of %M, %Y') as ddate from logindetails a,transactionentry b where a.User_Id=b.User_Id and groupid="+c+" order by termno";
                display(entry);
           }
           
              else    JOptionPane.showMessageDialog(null,"Entry Failed");
        }
           else JOptionPane.showMessageDialog(null,"Transaction already exist");
        }
        else    JOptionPane.showMessageDialog(null,"Fields Should not left blank");

      
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        row=jTable1.getSelectedRow();
        gid=jTable1.getModel().getValueAt(row, 0).toString();

        uid=jTable1.getModel().getValueAt(row, 1).toString();
        termno=jTable1.getModel().getValueAt(row,4).toString();
        int i=JOptionPane.showConfirmDialog(null,"Are you sure to remove??","Remove",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {

            if(new CommTransactionOperations().update(Integer.parseInt(gid),Integer.parseInt(uid),Integer.parseInt(termno)))
            {
                JOptionPane.showMessageDialog(null,"Removed");
                Update.setEnabled(false);
                 if(cbGId.getSelectedIndex()>0)
         {
            int c=Integer.parseInt((String) cbGId.getSelectedItem());
         String entry="Select a.User_Id,a.FirstName,a.LastName,b.groupid,b.termno,b.amount,date_format(b.depositdate,'%D of %M, %Y')as ddate from logindetails a,transactionentry b where a.User_Id=b.User_Id and groupid="+c+" order by termno";
         display(entry);
         }
           
            }
            else JOptionPane.showMessageDialog(null,"Remove Operation Failed");

        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void txtTermNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTermNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTermNoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                 Update.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtTermNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTermNoKeyTyped
        // TODO add your handling code here:
        char vchar=evt.getKeyChar();
	if(!(Character.isDigit(vchar)))
	{
		evt.consume();
	}
    }//GEN-LAST:event_txtTermNoKeyTyped

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        // TODO add your handling code here:
        char vchar=evt.getKeyChar();
	if(!(Character.isDigit(vchar)))
	{
		evt.consume();
	}
    }//GEN-LAST:event_txtAmountKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox cbGId;
    private javax.swing.JComboBox cbUId;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lGrpid;
    private designs.MyPanel myPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtTermNo;
    // End of variables declaration//GEN-END:variables
}
